### ISSUE TITLE
Issue 1: User can see their car

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an index.html, styles.css, and main.js file and link them together
- [x] Make a container for the game
- [x] Set size of game to the window size, ensure there are no margins , and set color
- [x] Create a place to hold the car and link to a car image
- [x] Place the car in the container
