### ISSUE TITLE
Issue 6 Users can choose their car model

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#11]
## 💰 Motivation

Our users should be able to choose their car!

## 📐 Plan

Create a modal carousel to show images of the vehicle and when the vehicle is selected the car image will change.

## ✅ Task List

- [x] Create a modal for the carousel.
- [x] Have a carousel of vehicels
  - [x] Create a container for the carousel items
  - [x] Create a place for each image of type of car
  - [x] have arrows and buttons to cycle through the vehicles
  - [x] have a button at the bottom to select
- [x] Once selected it should take the src of the current image that is not hidden
- [x] The src should be applied to the vehicle image source
- [x] Remove any unnecessary CSS
- [x] Test functionality
- [x] Fix any issues
