### ISSUE TITLE
Issue 2: User can turn their car

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create classes for the direction of the car
- [x] Listen for keyinputs(?) on the window
- [x] Create function to change the class of the car to change the direction it is facing
- [x] Adjust any CSS needed
- [x] Test the functionality
- [x] Fix any errors
