### ISSUE TITLE
Issue 3: User can start their car

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Figure out position of car
  - [x] Store the current position of the car
- [x] Add absolute position to image
- [x] Adjust offset for car so that it does not go out of window when turns
  - [x] Remove padding from container
- [x] Use an interval
  - [x] Create an intervalID variable
  - [x] create a function to move the vehicle from it's current position to the right
  - [x] Set the interval to happen every 16ms
- [x] Check for any unnecessary CSS
- [x] Test functionality
- [x] Fix any issues
