### ISSUE TITLE
Issue 4: User can stop their car

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Listen for an event on the window for keydown
- [x] Create a variable for car moving with a boolean value
  - [x] create a function to stop the car
  - [x] in the function clear the interval that is moving the car
  - [x] Use a condition to stop the car if the right key is pressed
- [x] Remove any unnecessary CSS
- [x] Test functionality
- [x] Fix any errors
