### ISSUE TITLE
Issue 5: User can steer their car

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Modify moveCar and moveRight functions
- [x] Create a countVer variable set to 1
- [x] Move car should check where the car is facing before starting the interval
- [x] Change move right function to be able to move in any direction
  - [x] Use condition to check which way the car is facing and then adjust top, right, bottom, or left
- [x] Remove any unnecessary CSS
- [x] test Functionality
- [x] Fix any issues
